### ISSUE TITLE
Change Planet Fitness to OneLife

### ISSUE THREAD

**Issue by tristan-f-r** [willuhmjs/overwatch#1]
OneLife >>>

**Comment by willuhmjs** [comment]
I considered adding OneLife Fitness initially, but after some research I discovered it is a regional chain. I'll still add it since multiple people have requested it. Added by [80a6d9f](https://github.com/willuhmjs/overwatch/commit/80a6d9fabdb824176d7c9ee5bd2374d38b66a573).
